### ISSUE TITLE
how to use it in JS

### ISSUE THREAD

**Issue by ctf0** [jfcherng/Sublime-TypeShort#1]
hi there, many thanx for this plugin its a big time saver, right now am trying to use it in `JS` files

i have tried `"syntax_list": ["JS"]` , `"syntax_list": ["JavaScript"]`  but with no luck, so any notes on how to fix that ?

**Comment by jfcherng** [comment]
The `syntax_list` is filled with `syntaxes` which are shown on the bottom-right corner of your ST window.

![2015-11-30_03-00-55](https://cloud.githubusercontent.com/assets/6594915/11459312/a1ffb4b8-970e-11e5-8c52-21bdc4caa454.png)

In my case, I have `"syntax_list": ["JavaScript", "JavaScript (Babel)"]`.
`"JavaScript"` is not needed but I prefer to add it.

**Comment by ctf0** [comment]
aha, thats why, wouldnt it be better if we used the scope it self rather than the language name that show up in the right corner, this way it doesnt matter which package u use you will always get the same result :)

**Comment by jfcherng** [comment]
Yes, I agree.

**Comment by jfcherng** [comment]
Add this feature in v1.1.0.
Now we can use `source.js` in the `syntax_list` as well.

**Comment by ctf0** [comment]
sweet, many thanx :+1:

**Comment by ctf0** [comment]
sorry for bringing this up again, but after some tests currently i can use something like `laravel-blade` which was working fine before the update.

**Comment by jfcherng** [comment]
Do you mean you `can't` use something like laravel-blade?

Would you please explain what `laravel-blade` means more specifically?
It's a plugin or.. what?
I mean, how can I reproduce it?

**Comment by ctf0** [comment]
its a syntax package for laravel https://packagecontrol.io/packages/Laravel%20Blade%20Highlighter , install it and try to use the type short with it.

**Comment by jfcherng** [comment]
Mmm.. the syntax of this package is `blade` rather than `Laravel Blade`.
That is out of my expectation.

**Comment by jfcherng** [comment]
Currently, I can't find a way to get the string which is exactly shown on the bottom-right corner of ST.
I add a debug option to help people finding out what should they use in the `syntax_list`.

In your case, its `blade`.

**Comment by ctf0** [comment]
you can use `scope hunter` which helps a lot in this cases, and you will find the scope first line in the panel :).

**Comment by jfcherng** [comment]
Thanks. I know that and it was written in the last release message as well.
