### ISSUE TITLE
Replacement action does not work in new view of a file

### ISSUE THREAD

**Issue by cpkio** [jfcherng/Sublime-TypeShort#4]

**Comment by jfcherng** [comment]
Could you elaborate on that?

**Comment by cpkio** [comment]
Well, it's simple as that. If you open a new view to a file already opened, then TypeShort works in original window and is not working in a «new view».

**Comment by jfcherng** [comment]
Okay, I get it!

Fixed in `1.14.1` via 23b03b38c8432ba17038413239eedb13400b7954.
